### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by tomodachi94** [CCSMB/Standards#11]
What license should this be licensed under?

I think it should be the GFDL, as the predecessor to this was also GDFL.

**Comment by Ocawesome101** [comment]
GFDL sounds good.  [here it is for those who'd like to read it](https://github.com/CCSMB/Standards/issues/11).

**Comment by Ocawesome101** [comment]
as #12 points out, GFDL is in fact _required_ - at least for the standards written by Oeed.

**Comment by tomodachi94** [comment]
> GFDL sounds good. [here it is for those who'd like to read it](https://github.com/CCSMB/Standards/issues/11).

Did you intend for this link in this issue to link back to the issue?

**Comment by Ocawesome101** [comment]
whoops, no
